# Generated by Django 4.2.28 on 2026-02-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolanaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('liquidity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('age_seconds', models.PositiveIntegerField(default=0)),
                ('holders_count', models.PositiveIntegerField(default=0)),
                ('dev_hold_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top_10_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bundle_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sniper_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pro_holders_count', models.PositiveIntegerField(default=0)),
                ('is_passing_filter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
