# Generated by Django 4.2.28 on 2026-02-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solanatoken',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
